#!/usr/bin/env node
/**
 * make-fonts.mjs — self-host Fraunces and Newsreader, so the site makes no
 * third-party request at all.
 *
 * WHY. The privacy audit found that `fonts.googleapis.com` and `fonts.gstatic.com`
 * were the ONLY third-party requests these pages made — and they made them on every
 * page load, disclosing each reader's IP address and user agent to Google before a
 * word was read. Everything else on the site is first-party or a link the reader
 * chooses to follow.
 *
 * The privacy policy at /privacy claims the site makes no third-party requests. That
 * claim is a statement about this code, so it is enforced by `check-metadata.mjs`
 * rather than trusted: a page reintroducing a Google Fonts tag fails a gate.
 *
 * THE "SHARED CDN CACHE" ARGUMENT IS DEAD. It used to be true that a reader arrived
 * with Google's fonts already cached from another site. Browsers partitioned the HTTP
 * cache per top-level site in 2020, for privacy reasons — so every site pays for its
 * own copy either way, and hot-linking now buys nothing but the data flow.
 *
 * IDENTICAL COVERAGE, ONE FEWER PARTY. All three subsets Google served are kept —
 * latin, latin-ext and vietnamese — with Google's own `unicode-range` values, so
 * glyph coverage is byte-for-byte what it was. Vietnamese is dead weight for a site
 * with no Vietnamese in it, and it stays anyway: `unicode-range` means a reader never
 * downloads it, and dropping it would make self-hosting a behaviour change rather
 * than a substitution.
 *
 * WHAT NEITHER FAMILY HAS IS GREEK. Google offers no greek subset for either, so the
 * Sappho on /flower-codes — ἰόπλοκος — already rendered in a system fallback before
 * this change and still does. Pre-existing, not introduced here.
 *
 * THE AXIS SPEC LIVES HERE because it is editorial: Fraunces' WONK axis is the type
 * argument of the whole site, and which axes we ask for is a decision, not a fact to
 * be scraped back out of the markup this tool is about to clean.
 *
 *     node tools/make-fonts.mjs
 *
 * Writes: fonts/*.woff2, the @font-face block inside queering.css, tools/font-files.json
 */

import { writeFile, readFile, mkdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

const SPEC =
  'https://fonts.googleapis.com/css2' +
  '?family=Fraunces:ital,opsz,wght,SOFT,WONK@0,9..144,400..700,0..100,0..1;1,9..144,400..700,0..100,0..1' +
  '&family=Newsreader:ital,opsz,wght@0,6..72,400..700;1,6..72,400..700' +
  '&display=swap';

// woff2 is served only to a UA that admits it supports woff2.
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
           '(KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36';

const BEGIN = '/* ── BEGIN generated by tools/make-fonts.mjs — do not edit by hand ────────── */';
const END   = '/* ── END generated by tools/make-fonts.mjs ───────────────────────────────── */';

const css = await (await fetch(SPEC, { headers: { 'User-Agent': UA } })).text();
if (!css.includes('@font-face')) throw new Error('Google returned no @font-face blocks; check SPEC');

// Google emits a `/* subset */` comment before each block. Walk the file in order so
// each block keeps the subset name that precedes it.
const faces = [];
let subset = null;
for (const part of css.split(/(\/\*[^*]*\*\/)/)) {
  const c = /^\/\*\s*(.+?)\s*\*\/$/.exec(part.trim());
  if (c) { subset = c[1]; continue; }
  for (const m of part.matchAll(/@font-face\s*{([^}]*)}/g)) {
    const b = m[1];
    const get = (re) => (re.exec(b) || [])[1];
    faces.push({
      subset,
      family: get(/font-family:\s*'([^']+)'/),
      style: get(/font-style:\s*(\w+)/) ?? 'normal',
      weight: get(/font-weight:\s*([^;]+);/)?.trim() ?? '400',
      url: get(/url\(([^)]+)\)/),
      range: get(/unicode-range:\s*([^;]+);/)?.trim(),
    });
  }
}
if (!faces.length) throw new Error('parsed no @font-face blocks');

await mkdir(join(ROOT, 'fonts'), { recursive: true });

const manifest = {};
const blocks = [];
let total = 0;
console.log();
for (const f of faces) {
  const slug = `${f.family.toLowerCase()}-${f.style === 'italic' ? 'italic-' : ''}${f.subset}`;
  const file = `${slug}.woff2`;
  const buf = Buffer.from(await (await fetch(f.url, { headers: { 'User-Agent': UA } })).arrayBuffer());
  if (buf.length < 1000) throw new Error(`${file} came back ${buf.length} bytes — refusing to write a stub`);
  await writeFile(join(ROOT, 'fonts', file), buf);
  manifest[file] = { sha256: createHash('sha256').update(buf).digest('hex'), bytes: buf.length,
                     family: f.family, style: f.style, subset: f.subset };
  total += buf.length;
  console.log(`  ${file.padEnd(38)} ${String(Math.round(buf.length / 1024)).padStart(4)} KB`);
  blocks.push(
    `/* ${f.family} ${f.style} · ${f.subset} */\n` +
    `@font-face {\n` +
    `  font-family: '${f.family}';\n` +
    `  font-style: ${f.style};\n` +
    `  font-weight: ${f.weight};\n` +
    `  font-display: swap;\n` +
    `  src: url(fonts/${file}) format('woff2');\n` +
    `  unicode-range: ${f.range};\n` +
    `}`
  );
}

const generated = [
  BEGIN,
  '/* Self-hosted so the site makes no third-party request. Google served exactly these',
  '   subsets and exactly these unicode-range values; keeping both means glyph coverage',
  '   is unchanged and only the party serving them is. Regenerate with:',
  '       node tools/make-fonts.mjs',
  '   Never hand-edit below this line — and never add a fonts.googleapis.com link back',
  '   to a page: /privacy claims there are no third-party requests, and',
  '   check-metadata.mjs enforces that claim. */',
  '',
  ...blocks,
  '',
  END,
].join('\n');

const sheet = await readFile(join(ROOT, 'queering.css'), 'utf8');
let next;
if (sheet.includes(BEGIN)) {
  next = sheet.replace(new RegExp(`${BEGIN.replace(/[.*+?^${}()|[\]\\/]/g, '\\$&')}[\\s\\S]*?${END.replace(/[.*+?^${}()|[\]\\/]/g, '\\$&')}`), generated);
} else {
  // First run: the block goes above :root, so the faces are declared before anything
  // asks for them.
  const at = sheet.indexOf(':root {');
  if (at < 0) throw new Error('cannot find :root in queering.css');
  next = sheet.slice(0, at) + generated + '\n\n' + sheet.slice(at);
}
await writeFile(join(ROOT, 'queering.css'), next);
await writeFile(join(ROOT, 'tools', 'font-files.json'),
                JSON.stringify(manifest, null, 2) + '\n');

console.log(`\n  ${faces.length} face(s) · ${(total / 1048576).toFixed(2)} MB in fonts/`);
const latin = Object.values(manifest).filter((m) => m.subset === 'latin')
  .reduce((n, m) => n + m.bytes, 0);
console.log(`  a latin-only reader downloads ${Math.round(latin / 1024)} KB of it`);
console.log('\nWrote fonts/, the @font-face block in queering.css, and tools/font-files.json.');
console.log('Now remove the Google Fonts tags from the pages, and commit all of it.');
