#!/usr/bin/env node
/**
 * make-csp.mjs — write the Content-Security-Policy into `_headers`, hashes and all.
 *
 * WHY IT IS GENERATED. The policy names a sha256 of the inline snippet every page runs
 * before first paint — the one that applies the stored ground and the stored view before
 * the reader is shown anything. That snippet lists the nine typefaces the picker offers, so
 * `make-fonts.mjs` narrowing the picker CHANGES IT, and a hand-kept hash would go stale in
 * the same commit.
 *
 * THE FAILURE THAT WOULD CAUSE IS THE WORST ONE AVAILABLE HERE. A stale hash does not warn:
 * the browser simply refuses to run the snippet, on every page, and every reader who had
 * asked for the cabinet or for plain view gets the other thing flashed at them before the
 * stylesheet catches up. That is precisely the failure `_headers` already carries a comment
 * about — it was the stated reason this site shipped `frame-ancestors` and nothing else for
 * months — and it would arrive silently, visible only to somebody who had a preference
 * stored and was looking for it.
 *
 * JSON-LD IS NOT SCRIPT. Twenty-eight pages carry a `<script type="application/ld+json">`
 * block and not one of them needs a hash: a data block is never executed, so `script-src`
 * has no opinion about it. Hashing them would have put twenty-eight useless hashes in the
 * header and hidden the one that matters among them.
 *
 * `style-src` KEEPS 'unsafe-inline' AND THAT IS NOT LAZINESS. There are 1,299 inline
 * `style=` attributes on this site, carrying each sheet's own foxing seed, its stamp
 * rotation and its card colours — and **CSP hashes do not cover style attributes**, only
 * `<style>` elements. The alternative is not a stricter policy, it is deleting the per-page
 * palette. Script injection is the valuable target and it is fully locked; there is no user
 * input on this site to inject style through in the first place.
 *
 *     node tools/make-csp.mjs           # write it
 *     node tools/make-csp.mjs --check   # exit 1 if _headers disagrees with the pages
 */
import { readFile, writeFile, readdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');
const OPEN = '  # >>> csp — generated by tools/make-csp.mjs; do not hand-edit this line';
const CLOSE = '  # <<< csp';

/** Every distinct executable inline script on the site, as a CSP hash source. */
export async function scriptHashes() {
  const files = (await readdir(ROOT)).filter((f) => f.endsWith('.html')).sort();
  const seen = new Map();
  for (const f of files) {
    const html = await readFile(join(ROOT, f), 'utf8');
    for (const m of html.matchAll(/<script([^>]*)>([\s\S]*?)<\/script>/g)) {
      const [, attrs, body] = m;
      if (/\ssrc=/.test(attrs)) continue;                     // external: covered by 'self'
      if (/type=["']application\/ld\+json["']/.test(attrs)) continue;  // data, never executed
      const h = `'sha256-${createHash('sha256').update(body, 'utf8').digest('base64')}'`;
      if (!seen.has(h)) seen.set(h, []);
      seen.get(h).push(f);
    }
  }
  return seen;
}

function policy(hashes) {
  return [
    "default-src 'self'",
    "base-uri 'none'",
    "object-src 'none'",
    "form-action 'none'",
    "frame-ancestors 'none'",
    "img-src 'self'",
    "font-src 'self'",
    "connect-src 'self'",
    /* The one embed, and it is click-to-load: the served markup holds a poster we drew and
       a plain link, and queering-embed.js upgrades that link on a press. */
    'frame-src https://www.youtube-nocookie.com',
    "style-src 'self' 'unsafe-inline'",
    `script-src 'self' ${[...hashes.keys()].sort().join(' ')}`,
  ].join('; ');
}

const hashes = await scriptHashes();
if (!hashes.size) {
  console.error('\nFAIL — no executable inline script found. That is not plausible on this\n' +
                'site: every page runs one before first paint. Something is wrong with the\n' +
                'scan rather than with the pages.\n');
  process.exit(1);
}

const line = `  Content-Security-Policy: ${policy(hashes)}`;
const raw = await readFile(join(ROOT, '_headers'), 'utf8');
const i = raw.indexOf(OPEN), j = raw.indexOf(CLOSE);
if (i < 0 || j < 0) {
  console.error(`\nFAIL — the markers are missing from _headers. Expected:\n${OPEN}\n${CLOSE}\n`);
  process.exit(1);
}
const next = raw.slice(0, i + OPEN.length) + '\n' + line + '\n' + raw.slice(j);

console.log();
for (const [h, pages] of hashes) console.log(`  ${h}  on ${pages.length} page(s)`);

if (CHECK) {
  if (next === raw) { console.log('\nPASS — the policy in _headers matches the pages.\n'); process.exit(0); }
  console.error('\nFAIL — the Content-Security-Policy in _headers no longer matches the pages.\n' +
                'A stale script hash is silent: the browser refuses the before-paint snippet on\n' +
                'every page and every reader with a stored preference sees the wrong ground\n' +
                'flash. Run: node tools/make-csp.mjs\n\nIt should read:\n' + line + '\n');
  process.exit(1);
}

if (next === raw) console.log('\nThe policy was already current. Nothing written.\n');
else { await writeFile(join(ROOT, '_headers'), next); console.log('\nWrote the policy into _headers. Commit it.\n'); }
