#!/usr/bin/env node
/**
 * make-fonts.mjs — self-host Fraunces and Newsreader, so the site makes no
 * third-party request at all.
 *
 * WHY. The privacy audit found that `fonts.googleapis.com` and `fonts.gstatic.com`
 * were the ONLY third-party requests these pages made — and they made them on every
 * page load, disclosing each reader's IP address and user agent to Google before a
 * word was read. Everything else on the site is first-party or a link the reader
 * chooses to follow.
 *
 * The privacy policy at /privacy claims the site makes no third-party requests. That
 * claim is a statement about this code, so it is enforced by `check-metadata.mjs`
 * rather than trusted: a page reintroducing a Google Fonts tag fails a gate.
 *
 * THE "SHARED CDN CACHE" ARGUMENT IS DEAD. It used to be true that a reader arrived
 * with Google's fonts already cached from another site. Browsers partitioned the HTTP
 * cache per top-level site in 2020, for privacy reasons — so every site pays for its
 * own copy either way, and hot-linking now buys nothing but the data flow.
 *
 * IDENTICAL COVERAGE, ONE FEWER PARTY. All three subsets Google served are kept —
 * latin, latin-ext and vietnamese — with Google's own `unicode-range` values, so
 * glyph coverage is byte-for-byte what it was. Vietnamese is dead weight for a site
 * with no Vietnamese in it, and it stays anyway: `unicode-range` means a reader never
 * downloads it, and dropping it would make self-hosting a behaviour change rather
 * than a substitution.
 *
 * WHAT NEITHER FAMILY HAS IS GREEK. Google offers no greek subset for either, so the
 * Sappho on /flower-codes — ἰόπλοκος — already rendered in a system fallback before
 * this change and still does. Pre-existing, not introduced here.
 *
 * THE AXIS SPEC LIVES HERE because it is editorial: Fraunces' WONK axis is the type
 * argument of the whole site, and which axes we ask for is a decision, not a fact to
 * be scraped back out of the markup this tool is about to clean.
 *
 *     node tools/make-fonts.mjs
 *
 * THE LICENCE TRAVELS WITH THE FILES. Both families are under the SIL Open Font
 * Licence, which requires the licence text to accompany the fonts wherever they are
 * redistributed — and a public repository serving woff2 over HTTP is redistribution.
 * The repo shipped them for a day without it. So this tool now fetches each family's
 * own OFL.txt and its upstream designer credit and writes them beside the faces:
 * a generic copy of the licence with the wrong copyright line would not be compliance,
 * it would be a gesture at it.
 *
 * The designer names come from upstream METADATA rather than from memory, because on
 * this site an attribution taken from recollection is the characteristic fault.
 *
 * Writes: fonts/*.woff2, fonts/<Family>-OFL.txt, fonts/README.md,
 *         the @font-face block inside queering.css, tools/font-files.json
 */

import { writeFile, readFile, mkdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

const SPEC =
  'https://fonts.googleapis.com/css2' +
  '?family=Fraunces:ital,opsz,wght,SOFT,WONK@0,9..144,400..700,0..100,0..1;1,9..144,400..700,0..100,0..1' +
  '&family=Newsreader:ital,opsz,wght@0,6..72,400..700;1,6..72,400..700' +
  '&display=swap';

// woff2 is served only to a UA that admits it supports woff2.
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
           '(KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36';

const BEGIN = '/* ── BEGIN generated by tools/make-fonts.mjs — do not edit by hand ────────── */';
const END   = '/* ── END generated by tools/make-fonts.mjs ───────────────────────────────── */';

const css = await (await fetch(SPEC, { headers: { 'User-Agent': UA } })).text();
if (!css.includes('@font-face')) throw new Error('Google returned no @font-face blocks; check SPEC');

// Google emits a `/* subset */` comment before each block. Walk the file in order so
// each block keeps the subset name that precedes it.
const faces = [];
let subset = null;
for (const part of css.split(/(\/\*[^*]*\*\/)/)) {
  const c = /^\/\*\s*(.+?)\s*\*\/$/.exec(part.trim());
  if (c) { subset = c[1]; continue; }
  for (const m of part.matchAll(/@font-face\s*{([^}]*)}/g)) {
    const b = m[1];
    const get = (re) => (re.exec(b) || [])[1];
    faces.push({
      subset,
      family: get(/font-family:\s*'([^']+)'/),
      style: get(/font-style:\s*(\w+)/) ?? 'normal',
      weight: get(/font-weight:\s*([^;]+);/)?.trim() ?? '400',
      url: get(/url\(([^)]+)\)/),
      range: get(/unicode-range:\s*([^;]+);/)?.trim(),
    });
  }
}
if (!faces.length) throw new Error('parsed no @font-face blocks');

/* ── The picker families ───────────────────────────────────────────────────────
 * The nine faces offered under Reading. Chosen by Ryan from two specimen sheets on
 * 2026-09-10; the reasoning is in the register and the specimen is scratch.
 *
 * `body: true` means the family has a REAL italic and can set the reading face as well
 * as the display one. That distinction is not taste — it is forced. Victorianna ships
 * Thin alone and is unreadable at 19px; Redaction Inclusive, Insolente, Trickster and
 * Sporting Grotesque have no italic at all, so setting them as the body face would put
 * a faux slant on every `<cite>` on a site built out of citations. Those five set the
 * display face and leave Newsreader to read.
 *
 * THE CUTS ARE THE TEXT CUTS. The first specimen showed Adelphe as Floréal Bold,
 * Coxinel·le as Black and Sporting Grotesque as Bold, because those sorted first in
 * their repositories — three families misrepresented as display faces when they are
 * full text families. Regular, Italic and Bold here.
 *
 * NO SUBSETTING FOR THE CUTE FAMILIES. Its conditions forbid deleting the post-binary
 * characters or the OpenType features that activate them, so the Bye Bye Binary faces
 * ship whole. Atkinson is OFL and takes Google's latin subset.
 *
 * NOTHING HERE IS LOADED UNTIL IT IS PICKED. An @font-face declaration costs only its
 * own bytes of CSS; the file is fetched when a rule using the family first matches
 * rendered text. So all nine are declared and a reader who picks none downloads none.
 */
const BBB = 'https://gitlab.com/bye-bye-binary';
const VLV = 'https://raw.githubusercontent.com/velvetyne';

const PICKER = [
  { id: 'baskervvol', family: 'BBB Baskervvol', body: true,
    by: 'Bye Bye Binary', licence: 'CUTE', source: `${BBB}/baskervvol`,
    licenceUrl: `${BBB}/baskervvol/-/raw/HEAD/2024_BBB_CUTE-EN.pdf`, licenceExt: 'pdf',
    cuts: [['regular', 'normal', '400', `${BBB}/baskervvol/-/raw/HEAD/otf/BBBBaskervvol-Regular.otf`],
           ['italic',  'italic', '400', `${BBB}/baskervvol/-/raw/HEAD/otf/BBBBaskervvol-Italic.otf`],
           ['bold',    'normal', '700', `${BBB}/baskervvol/-/raw/HEAD/otf/BBBBaskervvol-Bold.otf`]] },

  { id: 'adelphe', family: 'Adelphe', body: true,
    by: 'Bye Bye Binary', licence: 'CUTE, stated in the README upstream', source: `${BBB}/adelphe`,
    licenceUrl: `${BBB}/adelphe/-/raw/HEAD/README.md`,
    cuts: [['regular', 'normal', '400', `${BBB}/adelphe/-/raw/HEAD/otf/Adelphe-FlorealRegular.otf`],
           ['italic',  'italic', '400', `${BBB}/adelphe/-/raw/HEAD/otf/Adelphe-FlorealItalic.otf`],
           ['bold',    'normal', '700', `${BBB}/adelphe/-/raw/HEAD/otf/Adelphe-FlorealBold.otf`]] },

  { id: 'coxinelle', family: 'Coxinelle', body: true,
    by: 'Bye Bye Binary', licence: 'CUTE', source: `${BBB}/coxinel-le`,
    licenceUrl: `${BBB}/coxinel-le/-/raw/HEAD/Licence.pdf`, licenceExt: 'pdf',
    cuts: [['regular', 'normal', '400', `${BBB}/coxinel-le/-/raw/HEAD/otf/Coxinelle-Regular.otf`],
           ['italic',  'italic', '400', `${BBB}/coxinel-le/-/raw/HEAD/otf/Coxinelle-Italic.otf`],
           ['bold',    'normal', '700', `${BBB}/coxinel-le/-/raw/HEAD/otf/Coxinelle-Bold.otf`]] },

  { id: 'atkinson', family: 'Atkinson Hyperlegible', body: true, google: 'Atkinson+Hyperlegible',
    by: 'Braille Institute of America', licence: 'OFL-1.1',
    source: 'https://github.com/googlefonts/atkinson-hyperlegible',
    licenceUrl: 'https://raw.githubusercontent.com/google/fonts/main/ofl/atkinsonhyperlegible/OFL.txt' },

  { id: 'redaction', family: 'Redaction Inclusive', body: false,
    by: 'Bye Bye Binary, after Redaction by Jeremy Mickel / MCKL', licence: 'OFL-1.1',
    source: `${BBB}/redaction-inclusive`,
    licenceUrl: `${BBB}/redaction-inclusive/-/raw/HEAD/OFL.txt`,
    cuts: [['regular', 'normal', '400', `${BBB}/redaction-inclusive/-/raw/HEAD/fonts/webfonts/Redaction-Inclusive-Regular.woff2`]] },

  { id: 'insolente', family: 'Insolente', body: false,
    by: 'Bye Bye Binary', licence: 'CUTE, stated in the README upstream', source: `${BBB}/insolente`,
    licenceUrl: `${BBB}/insolente/-/raw/HEAD/README.md`,
    cuts: [['regular', 'normal', '400', `${BBB}/insolente/-/raw/HEAD/otf/Insolente-Regular.otf`]] },

  { id: 'trickster', family: 'Trickster', body: false,
    by: 'Jean-Baptiste Morizot, Velvetyne', licence: 'OFL-1.1',
    source: 'https://github.com/velvetyne/Trickster',
    licenceUrl: `${VLV}/Trickster/HEAD/LICENSE.txt`,
    cuts: [['regular', 'normal', '400', `${VLV}/Trickster/HEAD/webfonts/Trickster-Regular.woff2`]] },

  { id: 'victorianna', family: 'Victorianna', body: false,
    by: 'Velvetyne', licence: 'OFL-1.1', source: 'https://github.com/velvetyne/Victorianna',
    licenceUrl: `${VLV}/Victorianna/HEAD/LICENSE.txt`,
    cuts: [['regular', 'normal', '400', `${VLV}/Victorianna/HEAD/fonts/VictoriannaThin_Desktop_OTF/VTF%20victorianna%20thin.otf`],
           ['italic',  'italic', '400', `${VLV}/Victorianna/HEAD/fonts/VictoriannaThin_Desktop_OTF/VTF%20victorianna%20thin%20talic.otf`]] },

  { id: 'sporting', family: 'Sporting Grotesque', body: false,
    by: 'Lucas Le Bihan, Velvetyne', licence: 'OFL-1.1',
    source: 'https://github.com/velvetyne/Sporting-Grotesque',
    licenceUrl: `${VLV}/Sporting-Grotesque/HEAD/LICENSE.txt`,
    cuts: [['regular', 'normal', '400', `${VLV}/Sporting-Grotesque/HEAD/webfonts/Regular/Sporting_Grotesque-Regular_web.woff2`],
           ['bold',    'normal', '700', `${VLV}/Sporting-Grotesque/HEAD/webfonts/Bold/Sporting_Grotesque-Bold_web.woff2`]] },
];

await mkdir(join(ROOT, 'fonts'), { recursive: true });

const manifest = { files: {}, families: {} };
const blocks = [];
let total = 0;
console.log();
for (const f of faces) {
  const slug = `${f.family.toLowerCase()}-${f.style === 'italic' ? 'italic-' : ''}${f.subset}`;
  const file = `${slug}.woff2`;
  const buf = Buffer.from(await (await fetch(f.url, { headers: { 'User-Agent': UA } })).arrayBuffer());
  if (buf.length < 1000) throw new Error(`${file} came back ${buf.length} bytes — refusing to write a stub`);
  await writeFile(join(ROOT, 'fonts', file), buf);
  manifest.files[file] = { sha256: createHash('sha256').update(buf).digest('hex'), bytes: buf.length,
                           family: f.family, style: f.style, subset: f.subset };
  total += buf.length;
  console.log(`  ${file.padEnd(38)} ${String(Math.round(buf.length / 1024)).padStart(4)} KB`);
  blocks.push(
    `/* ${f.family} ${f.style} · ${f.subset} */\n` +
    `@font-face {\n` +
    `  font-family: '${f.family}';\n` +
    `  font-style: ${f.style};\n` +
    `  font-weight: ${f.weight};\n` +
    `  font-display: swap;\n` +
    `  src: url(fonts/${file}) format('woff2');\n` +
    `  unicode-range: ${f.range};\n` +
    `}`
  );
}

/* ── download the picker families and emit their faces and their class rules ──── */
const pickerFaces = [];
const pickerRules = [];
for (const f of PICKER) {
  let cuts = [];

  if (f.google) {
    /* OFL, so Google's latin subset is fine here — the no-subsetting condition is
       CUTE's and applies to the Bye Bye Binary faces only. */
    const css = await (await fetch(
      `https://fonts.googleapis.com/css2?family=${f.google}:ital,wght@0,400;0,700;1,400;1,700&display=swap`,
      { headers: { 'User-Agent': UA } })).text();
    let subset = null;
    for (const part of css.split(/(\/\*[^*]*\*\/)/)) {
      const c = /^\/\*\s*(.+?)\s*\*\/$/.exec(part.trim());
      if (c) { subset = c[1]; continue; }
      for (const m of part.matchAll(/@font-face\s*{([^}]*)}/g)) {
        if (subset !== 'latin') continue;
        const b = m[1];
        const style = (/font-style:\s*(\w+)/.exec(b) || [])[1] ?? 'normal';
        const weight = (/font-weight:\s*([^;]+);/.exec(b) || [])[1]?.trim() ?? '400';
        const url = (/url\(([^)]+)\)/.exec(b) || [])[1];
        cuts.push([`${style === 'italic' ? 'italic' : 'roman'}-${weight}`, style, weight, url]);
      }
    }
    if (!cuts.length) throw new Error(`${f.family}: no latin faces in the Google CSS`);
  } else {
    cuts = f.cuts;
  }

  const files = [];
  for (const [cut, style, weight, url] of cuts) {
    const ext = /\.woff2($|\?)/.test(url) || url.includes('gstatic') ? 'woff2' : 'otf';
    const file = `${f.id}-${cut}.${ext}`;
    const buf = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
    if (buf.length < 2000) throw new Error(`${file} came back ${buf.length} bytes — refusing a stub`);
    await writeFile(join(ROOT, 'fonts', file), buf);
    manifest.files[file] = { sha256: createHash('sha256').update(buf).digest('hex'), bytes: buf.length,
                             family: f.family, style, subset: f.google ? 'latin' : 'full' };
    files.push({ file, style, weight, bytes: buf.length, format: ext === 'woff2' ? 'woff2' : 'opentype' });
    pickerFaces.push(
      `/* ${f.family} · ${cut} */\n@font-face {\n  font-family: '${f.family}';\n` +
      `  font-style: ${style};\n  font-weight: ${weight};\n  font-display: swap;\n` +
      `  src: url(fonts/${file}) format('${ext === 'woff2' ? 'woff2' : 'opentype'}');\n}`);
  }

  const stack = `'${f.family}', "Iowan Old Style", Georgia, serif`;
  pickerRules.push(
    `/* ${f.family} — ${f.by}. ${f.body ? 'Sets both faces: it has a real italic.'
      : 'Display only: no italic upstream, so Newsreader keeps the reading.'} */\n` +
    `html.qe-font-${f.id} {\n  --qe-display: ${stack};\n` +
    (f.body ? `  --qe-body: ${stack};\n` : '') + `}`);

  const ofl = await (await fetch(f.licenceUrl, { headers: { 'User-Agent': UA } })).arrayBuffer();
  const licFile = `${f.family.replace(/ /g, '')}-LICENCE.${f.licenceExt ?? 'txt'}`;
  await writeFile(join(ROOT, 'fonts', licFile), Buffer.from(ofl));
  manifest.families[f.family] = { designer: f.by, licence: f.licence, licence_file: licFile,
                                  upstream: f.source, picker_id: f.id, sets_body: !!f.body,
                                  cuts: files.map((x) => x.file) };
  const kb = files.reduce((n, x) => n + x.bytes, 0) / 1024;
  console.log(`  ${f.family.padEnd(24)} ${String(Math.round(kb)).padStart(4)} KB  ` +
              `${files.length} cut(s)  ${f.body ? 'display+body' : 'display only'}`);
}

const generated = [
  BEGIN,
  '/* Self-hosted so the site makes no third-party request. Google served exactly these',
  '   subsets and exactly these unicode-range values; keeping both means glyph coverage',
  '   is unchanged and only the party serving them is. Regenerate with:',
  '       node tools/make-fonts.mjs',
  '   Never hand-edit below this line — and never add a fonts.googleapis.com link back',
  '   to a page: /privacy claims there are no third-party requests, and',
  '   check-metadata.mjs enforces that claim. */',
  '',
  ...blocks,
  '',
  '/* ── The picker families, offered under Reading ───────────────────────────────',
  '   Declared, not loaded: an @font-face costs its own bytes of CSS and the file is',
  '   fetched only when a rule using the family first matches rendered text. A reader',
  '   who picks none downloads none of them. The class rules below are what the picker',
  '   switches, and both halves are generated from one table so they cannot disagree',
  '   about which families exist or which of them may set the reading face. */',
  '',
  ...pickerFaces,
  '',
  ...pickerRules,
  '',
  END,
].join('\n');

/* ── the licence and the credit, per family, from upstream ─────────────────────── */
const GH = 'https://raw.githubusercontent.com/google/fonts/main/ofl';
for (const family of [...new Set(faces.map((f) => f.family))]) {
  const slug = family.toLowerCase();
  const ofl = await (await fetch(`${GH}/${slug}/OFL.txt`)).text();
  if (!/Open Font License/i.test(ofl))
    throw new Error(`${family}: that does not look like an OFL. Refusing to write a licence file we cannot vouch for.`);
  const meta = await (await fetch(`${GH}/${slug}/METADATA.pb`)).text();
  const designer = (/designer:\s*"([^"]+)"/.exec(meta) || [])[1] ?? null;
  const copyright = (ofl.split('\n')[0] || '').trim();
  if (!designer) throw new Error(`${family}: no designer in upstream METADATA — do not guess one`);
  await writeFile(join(ROOT, 'fonts', `${family}-OFL.txt`), ofl);
  manifest.families[family] = { designer, copyright, licence: 'OFL-1.1',
                                licence_file: `${family}-OFL.txt`, upstream: `${GH}/${slug}/OFL.txt` };
  console.log(`  ${(family + '-OFL.txt').padEnd(38)} ${String(Math.round(ofl.length / 1024)).padStart(4)} KB   ${designer}`);
}

/* A README so the provenance is legible to a person opening the folder, not only to a
   tool reading JSON. Derived, so it cannot drift from what was actually downloaded. */
const readme = ['# fonts/', '',
  'Self-hosted so the site makes no third-party request. Generated by `tools/make-fonts.mjs`;',
  'do not edit by hand, and do not add a face without re-running it.', '',
  ...Object.entries(manifest.families).flatMap(([family, m]) => [
    `## ${family}`, '',
    `- **Designed by** ${m.designer}`,
    `- **${m.copyright}**`,
    `- Licensed under the SIL Open Font Licence 1.1 — see \`${m.licence_file}\`, which is`,
    `  included because the OFL requires the licence to travel with the fonts, and serving`,
    `  woff2 from a public repository is redistribution.`,
    `- Upstream: ${m.upstream.replace('/OFL.txt', '')}`, '',
  ]),
].join('\n');
await writeFile(join(ROOT, 'fonts', 'README.md'), readme);

const sheet = await readFile(join(ROOT, 'queering.css'), 'utf8');
let next;
if (sheet.includes(BEGIN)) {
  next = sheet.replace(new RegExp(`${BEGIN.replace(/[.*+?^${}()|[\]\\/]/g, '\\$&')}[\\s\\S]*?${END.replace(/[.*+?^${}()|[\]\\/]/g, '\\$&')}`), generated);
} else {
  // First run: the block goes above :root, so the faces are declared before anything
  // asks for them.
  const at = sheet.indexOf(':root {');
  if (at < 0) throw new Error('cannot find :root in queering.css');
  next = sheet.slice(0, at) + generated + '\n\n' + sheet.slice(at);
}
await writeFile(join(ROOT, 'queering.css'), next);
await writeFile(join(ROOT, 'tools', 'font-files.json'),
                JSON.stringify(manifest, null, 2) + '\n');

console.log(`\n  ${faces.length} face(s) · ${(total / 1048576).toFixed(2)} MB in fonts/`);
const latin = Object.values(manifest.files).filter((m) => m.subset === 'latin')
  .reduce((n, m) => n + m.bytes, 0);
console.log(`  a latin-only reader downloads ${Math.round(latin / 1024)} KB of it`);
console.log('\nWrote fonts/, the @font-face block in queering.css, and tools/font-files.json.');
console.log('Now remove the Google Fonts tags from the pages, and commit all of it.');
